### PR TITLE
Default scene doesn't work on Godot 3.2

### PR DESCRIPTION
**Pull request by ArturM**
Cloned repository does not work on stable Godot.

I made a few cosmetic changes to make it work.

### CODE REVIEW

**Comment by Beuc** [comment]
Hi @ArturM,

Just in case, the stable 2.0 version for Godot 3.2 is in branch "esc2-godot3".

Regarding your pull request, a few general guidelines, before @StraToN reviews it:
- 1 PR per fix / feature / translation
- Cosmetic changes / code linting in a separate PR
- Do not merge other PRs in your PR
- Explain what each error is, how one can reproduce it, and why the patch will fix the issue

**Comment by ArturM** [comment]
Hi @Beuc,

I'm new to GitHub - didin't know that commits after pull request are included automatically :)
Reverted some commits and now there are only commits required to make default demo run.

How to reproduce:
- Simply 'git clone' master branch, open it in Godot 3.2 and run project (F5)

Most of the changes are parentheses around assert() function arguments.

Function set_position() now has two arguments, so I added it in calls with default to 'false' - as it is in
parent Control class - https://docs.godotengine.org/en/3.2/classes/class_control.html#class-control-method-set-position

Also enum from AFAIR Godot 3.1 requires commas - so I've added it in global_vm.gd:22

It fixes #270 and #267

**Comment by StraToN** [comment]
Hi @ArturM and thanks for your PR. I'm fine with the fixes.

As @Beuc said above, we'll try to get a cleaner commits history in the future, so my remarks here mostly concern the number of commits in the PR. 

Yours has 2 commits, and the first one is actually a merge from upstream. You can eventually rebase your branch intereactively to squash these 2 commits into one using `git rebase -i`. You can read this page here for more explanations: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Thanks a lot :)

**Comment by ArturM** [comment]
I think I did it :)

**Comment by StraToN** [comment]
Thanks!

**Pull request merged**
