### PR TITLE
Improve dialog trees, documentation and default font

### LINKED ISSUE #40: cyrillic symbols in esc files
I want to use cyrillic symbols in esc files but when I run scene I can not see them.

### PR DESCRIPTION
**Pull request by fleskesvor**
Adds font with better [Unicode support](https://developers.googleblog.com/2016/10/an-open-source-font-system-for-everyone.html), which finally fixes #40.

I'm not 100% sure how to best respect the license (SIL Open Font License), but I included the original license file and readme in a separate font directory and put a note in our readme. Do you know if this is the best way, @StraToN, or should we ask Akien?

### CODE REVIEW

**Comment by mjtorn** [comment]
Tested in our jam game, it works with colors and shadow-as-outline.

IIRC the .tres files are project-specific, but I always find myself searching
for https://godotengine.org/qa/20870/how-do-you-bring-fonts-into-godot-3-0

Should that maybe be pointed out or have a pointer to the official docs
if they explain the thing?

Either way, good work, much appreciated!

**Comment by fleskesvor** [comment]
> Tested in our jam game, it works with colors and shadow-as-outline.

Thanks for testing. :slightly_smiling_face: 

> IIRC the .tres files are project-specific, but I always find myself searching
for https://godotengine.org/qa/20870/how-do-you-bring-fonts-into-godot-3-0
>
> Should that maybe be pointed out or have a pointer to the official docs

Good point. I will add a small doc on using and customizing dialogue, including fonts.

**Comment by fleskesvor** [comment]
Thanks guys. ❤️ 

My second commit should address #41. It's not perfect, but it's much better than what we have.

**Comment by fleskesvor** [comment]
I moved the section on speech dialog into the new document on dialogs, and adapted it to not repeat the things from the previous section. Anyone want to look over the changes before it's merged?

**Pull request merged**
