### PR TITLE
Fix tooltip_node wrong references

### LINKED ISSUE #302: Fix missing tooltip_node reference in ui_mouse_icons
Because of the latest work, a reference to tooltip_node got lost in the mouse icons UI.

### PR DESCRIPTION
**Pull request by StraToN**
Fixes #302

I had to move the tooltip_node reference from ESCGame to ESCMain because of the loading order induced.
I am not sure this is right though so I'm open to suggestions.

### CODE REVIEW

**Comment by dploeger** [comment]
What was your problem with the loading order? I simply corrected the reference in my Safehouse fork and it worked. 🤔

**Comment by StraToN** [comment]
When the room loads, the ESCTooltip scene _ready() command runs and tries to set 
```
escoria.main.current_scene.game.tooltip_node = self
```
But escoria.main.current_scene is null at this moment of the execution so it cannot hold the reference.

**Comment by dploeger** [comment]
Ahhh! So that's why it was lost after the compiler was rewritten.

How about we use a signal? Something like "scene_ready" or something and listen to it in the Tooltip? The process responsible for loading the scene will emit it once its ready.

**Comment by StraToN** [comment]
We could do that indeed. I'll come up with a correction commit a bit later

**Review by dploeger — APPROVED** [review]

**Comment by dploeger** [comment]
Great work! Thanks!

**Comment by StraToN** [comment]
Thanks! :)

**Pull request merged**
