### PR TITLE
Rename and expand tooltip_lang_default to development_lang

### PR DESCRIPTION
**Pull request by mjtorn**
A quick new config option I made. Tested with the demo scene. Works as expected.

I put this under `platform` and moved `tooltip_lang_default` there as well
for reasons explained in the commit messages.

Everything should be safe to fly because when `lockit.gd` is fixed, these
texts will be the base of translations anyway, so there shouldn't be a
discrepancy unless the game developer does strange things with the translation CSV.

### CODE REVIEW

**Comment by mjtorn** [comment]
When this gets merged, #45 needs to be updated with a comment that The Book(tm) needs an update for the path to the tooltip lang setting.

**Comment by fleskesvor** [comment]
Now that you've implemented the same "short circuit" for dialog text, would it make sense to use the same project setting for both and call it `development_lang` or something like that?

**Comment by fleskesvor** [comment]
Yeah, I'm hoping to dedicate some time to updating the Floss Manuals tutorial before the Adventure Jam in case anyone wants to use Escoria for that.

Looks like this should be good to go once you've made that change (and updated your documentation). :slight_smile:

**Comment by fleskesvor** [comment]
Awesome! 👍 Thanks for the contribution!

**Pull request merged**
