### PR TITLE
Use the "keep" stretch mode for HiDPI/Retina

### PR DESCRIPTION
**Pull request by mjtorn**
If I'd have had time to properly test these during the past two weeks or so, this would have been a part of #205 :/

### CODE REVIEW

**Comment by fleskesvor** [comment]
Why does your PR also set "resizable" and "fullscreen" to false? I agree that you usually shouldn't be able to resize a game window, but for convenience and until we have a settings template to change screen sizes, it might make testing easier to be able to resize windows?

**Comment by fleskesvor** [comment]
Ok, that makes sense. Do you think you could add a line or two to the export docs about which settings to set to what before exporting?

**Comment by mjtorn** [comment]
@fleskesvor are you ok with that documentation? I added some other tacit knowledge I've accrued over the months as well.

**Comment by mjtorn** [comment]
I hope this isn't seen as an abuse of my new superpowers, but this has been hanging for a while and is proven to work so I think it should go in. We can address documentation issues later if need be, but let's keep the balls rolling!

**Comment by fleskesvor** [comment]
Sorry for the late reply. Yes, that documentation is perfect. :+1: 

> I hope this isn't seen as an abuse of my new superpowers

No, there's no controversy here. Welcome onboard. :slightly_smiling_face:

**Pull request merged**
