### PR TITLE
Show tooltip, as controlled by AM, only when it has text

### PR DESCRIPTION
**Pull request by mjtorn**
The action-menu code interacts with showing the tooltip,
and if an item doesn't have tooltip text, but the tooltip
is configured to have a background, an empty background
would show up without this.

It's annoying and fortunately fixed now.

### CODE REVIEW

**Comment by fleskesvor** [comment]
Looks good to me. Is it possible to open the action menu while a tooltip is set, resulting in the tooltip not being hidden when it's supposed to as a result of this and the trigger in https://github.com/godotengine/escoria/blob/master/device/globals/action_menu.gd#L42 ?

**Comment by mjtorn** [comment]
I have not seen an issue with tooltips not being hidden when the action menu is opened.

**Comment by fleskesvor** [comment]
Ok. I'm wondering if it might be better to change

    if $"tooltip" and $"tooltip".text:
        $"tooltip".visible = p_visible

to

    if $"tooltip":
        $"tooltip".visible = p_visible and $"tooltip".text

to safe-guard against such scenarios though? Otherwise there's a chance calling `set_tooltip_visible(false)` to hide the tooltip might not be future-proof.

**Comment by mjtorn** [comment]
@fleskesvor agreed with your reasoning, force-pushed.

Of course I haven't had the opportunity to actually test it, but there's no reason it would fail.

Maybe later today or just hit merge on the sucker.

**Comment by mjtorn** [comment]
Hit it, flesk! I noticed no difference.

**Comment by fleskesvor** [comment]
Great, thanks! :+1:

**Pull request merged**
